### ISSUE TITLE
Running object detection from cameratopic 

### ISSUE THREAD

**Issue by NickMcKillip** [intel/ros_openvino_toolkit#26]
We are trying to run object detection from a camera topic. It is not from a realsense camera, but is structured as an image message.
And you documentation says "any ROS topic which is structured in image message"
I am getting the following errors.
[ WARNING ] No data received in CameraTopic instance
[ WARNING ] Failed to get frame from input_device.

**Comment by chaoli2** [comment]
@NickMcKillip 
Shall we know which branch you are using? And what is your camera topic's name?

BTW, We notice that currently there is some hard code in our project, when subscribing camera topic [here](https://github.com/intel/ros_openvino_toolkit/blob/fcf0f9d38cfca40ad3b08150c28e43e5537bc54d/dynamic_vino_lib/src/inputs/realsense_camera_topic.cpp#L40). We'll evaluate and submit topic remapping patch in future.

**Comment by NickMcKillip** [comment]
I'm using the master branch. The topics name is /front_camera/image_raw. I already noticed the hard coding as well and already changed it to our topic name, but still got the error.

**Comment by chaoli2** [comment]
@NickMcKillip 
Which launch file are you using? Have you update corresponding yaml like [this one](https://github.com/intel/ros_openvino_toolkit/blob/fcf0f9d38cfca40ad3b08150c28e43e5537bc54d/vino_launch/param/pipeline_object.yaml#L3)? Will you please change ```inputs: [RealSenseCamera]``` to ```inputs: [RealSenseCameraTopic]``` and have try.

**Comment by matteopantano** [comment]
@NickMcKillip 
@chaoli2 

Were you able to solve?

If I try to run one model I have the error:
`[ WARNING ] Failed to get frame from input_device`

My .yaml looks like the following:
```
Pipelines:
- name: object
  inputs: [StandardCamera]
  infers:
    - name: ObjectDetection
      model: /home/matteo/openvino_models/person-detection-retail-0013.xml
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 1
      confidence_threshold: 0.5
      enable_roi_constraint: true # set enable_roi_constraint to false if you don't want to make the inferred ROI (region of interest) constrained into the camera frame
    - name: PersonReidentification
      model: /home/matteo/openvino_models/person-reidentification-retail-0076.xml
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 1
      confidence_threshold: 0.7
  outputs: [ImageWindow, RosTopic, RViz]
  connects:
    - left: StandardCamera
      right: [ObjectDetection]
    - left: ObjectDetection
      right: [PersonReidentification]
    - left: PersonReidentification
      right: [ImageWindow, RosTopic, RViz]

Common:
  camera_topic: /usb_cam/image_raw
```
