### ISSUE TITLE
enable_roi_constraint parameter

### ISSUE THREAD

**Issue by ximenesfel** [intel/ros_openvino_toolkit#52]
Hi.

I need to use an ROI area from a frame after processing the Object detection model. I looked at ros-openvino code and try to understand where the enable_roi_constraint parameter was used but I'm not able to determine. This parameter was found in these files:

**ros_openvino_toolkit/dynamic_vino_lib/src/inferences/object_detection.cpp**
This is a parameter for Object detection object but it no used in constructor.

**ros_openvino_toolkit/dynamic_vino_lib/src/pipeline_manager.cpp**
This parameter is used in Object Detection method called createObjectDetection

**ros_openvino_toolkit/vino_param_lib/include/vino_param_lib/param_manager.h**

struct InferenceParams
  {
    std::string name;
    std::string engine;
    std::string model;
    std::string label;
    int batch;
    float confidence_threshold = 0.5;
    bool enable_roi_constraint = false;
  };

But Where the Object Detection inference use this information to pass in the pipeline only the ROI area?

Thanks in advance.

**Comment by LewisLiuPub** [comment]
Hi, @ximenesfel, 
in some previous versions of openvino toolkit, we found that some ROIs (getting from the detection inference) involve negative values as the start point, for example [-1, -3, 50, 100]. Point(-1, -3) is out of the range of the frame's pixels, which makes the sequential steps confusing. So, as a workaround, we set enable_roi_constraint to true to refine the ROI from [-1, -3, 50, 100] to [0, 0, 50, 100].

If you want to get the subframe only covered by the ROI, I think you can do this way:
1. use this package to do the corresponding inference, and get the ROIs you are interested in.
2. get the original frame which is used for inference in step1.
3. use CV API to get the subframe.
          auto roi = next_rois[i];
          auto clippedRect = roi & cv::Rect(0, 0, width_, height_);
          cv::Mat next_input = frame_(clippedRect);

**Comment by ximenesfel** [comment]
Hi @LewisLiuPub. Thanks for your detailed explanation. I'll try to implement your code explanation.

**Comment by ximenesfel** [comment]
Hi @LewisLiuPub. Looking at callback() method in pipeline.cpp:

```
void Pipeline::callback(const std::string& detection_name)
{
  auto detection_ptr = name_to_detection_map_[detection_name];


  detection_ptr->fetchResults();

  // set output
  for (auto pos = next_.equal_range(detection_name); pos.first != pos.second;
       ++pos.first)
  {

    std::string next_name = pos.first->second;
    // if next is output, then print
    if (output_names_.find(next_name) != output_names_.end())
    {
      // name_to_output_map_[next_name]->accept(*detection_ptr->getResult());
      detection_ptr->observeOutput(name_to_output_map_[next_name]);
    }
    else
    {
      auto detection_ptr_iter = name_to_detection_map_.find(next_name);

      if (detection_ptr_iter != name_to_detection_map_.end())
      {

        auto next_detection_ptr = detection_ptr_iter->second;

        for (int i = 0; i < detection_ptr->getResultsLength(); ++i)
        {
          const dynamic_vino_lib::Result* prev_result = detection_ptr->getLocationResult(i);
          auto clippedRect = prev_result->getLocation() & cv::Rect(0, 0, width_, height_);
          cv::Mat next_input = frame_(clippedRect);
          next_detection_ptr->enqueue(next_input, prev_result->getLocation());
        }
        
        if (detection_ptr->getResultsLength() > 0)
        {
          increaseInferenceCounter();
          next_detection_ptr->submitRequest();
        }
      }
    }

  }
  decreaseInferenceCounter();
  cv_.notify_all();
}
```
I think the callback method do a similar code that you presented. **Am I wrong?**

The pipeline manager call this method to make the inference for Object detection. I'm creating a new pipeline for openvino using the following structure:

```
Pipelines:
- name: my_model
  inputs: [StandardCamera]
  infers:
    - name: ObjectDetection
      model: path_to_model
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 16
      enable_roi_constraint: true
    - name: TextDetection
      model: /root/models/text_detection/text-detection-0004.xml
      engine: CPU
      label: to/be/set/xxx.labels
      batch: 16
  outputs: [ImageWindow]
  confidence_threshold: 0.5
  connects:
    - left: StandardCamera
      right: [ObjectDetection]
    - left: ObjectDetection
      right: [TextDetection]
    - left: TextDetection
      right: [ImageWindow]

OpenvinoCommon:
```
My objective is to detect an object in an image, obtain this ROI (Object detection bounding box) and pass this ROI to a text detection model (like described above).

I'm using the text recognition demo (https://github.com/opencv/open_model_zoo/tree/master/demos/text_detection_demo) to implement this new pipeline as reference. The object detection is running ok but when I inserted in the pipeline the TextDetection model and try to obtain the text detection rectangles number from detection, I'm receiving zero as text detection rectangles. So, I think the TextDetection model is not receiving the correct ROI information. **How can I verify if TextDetection is receiving the correct information?**

Thanks in advance.
